### ISSUE TITLE
aarch64 relese please...

### ISSUE THREAD

**Issue by wong-fi-hung** [vertoreum/vertoreum#1]
this is mean, when me trying to build the wallet and daemon in aarch64/arm64 is very very slow, and can take a hours to building any crypto coin wallet from source...

so, can you to help me and an other people who is the arm64 users..?
please...

**Comment by vertoreum** [comment]
https://github.com/TylerAnder/vertoreum/releases/download/v1.0.0/Vertoreum-Aarch64.tar.gz
Here it is, if other people also need it
